'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const arts=[{src:'assets/first-look-clean.png',title:'Prabhas & Triptii Dimri',alt:'Prabhas and Triptii Dimri — cleaned campaign photograph'},{src:'assets/vivek-clean.png',title:'Vivek Oberoi',alt:'Vivek Oberoi — cleaned campaign photograph'}];
const cast=[{name:'PRABHAS',image:0,position:'46% 13%'},{name:'TRIPTII DIMRI',image:0,position:'76% 17%'},{name:'VIVEK OBEROI',image:1,position:'48% 12%'}];
const audio=$('#soundtrack');audio.volume=.45;
let context,analyser,bins,mediaSource,energy=0,customURL,customName='',resumeAfterVideo=false,activeArt=0,sceneIndex=0,castVersion=0;
let reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;try{reduced||=localStorage.getItem('spirit-motion')==='reduce'}catch{}
document.body.classList.toggle('reduced',reduced);
const watch=(label='Watch the Sound Story')=>`<button class="watch" data-watch="telugu"><span class="play-ring">▶</span><span>${label}<small>TELUGU · 01:31</small></span></button>`;
const title=(manual=false)=>`<span data-spirit-title ${manual?'data-title-manual="true"':''} aria-label="Spirit"></span>`;
const sources=[['Film & production — T-Series','https://www.tseries.com/news/prabhas%E2%80%93sandeep-reddy-vanga%E2%80%99s-spirit-begins-filming-muhurat-held-hyderabad-chiranjeevi-chief'],['Telugu Sound Story — T-Series Telugu','https://www.youtube.com/watch?v=VCGVPiD4BP0'],['Hindi Sound Story — T-Series','https://www.youtube.com/watch?v=_YhSSfXmr9c'],['Campaign updates — inSpiritMode','https://www.instagram.com/inspiritmode/']];
$('#main').innerHTML=`
<section id="home" class="hero flow-scene"><div class="hero-images">${arts.slice(0,1).map((a,i)=>`<img class="scene ${i===0?'active':''}" data-scene="${i}" src="${a.src}" alt="${a.alt}" ${i===0?'fetchpriority="high"':'loading="lazy"'}>`).join('')}</div><div class="hero-shade"></div><div class="light-pass" aria-hidden="true"></div><div class="star-credit"><span>INDIA’S BIGGEST SUPERSTAR</span><strong>PRABHAS</strong></div><h1 class="hero-title">${title(true)}</h1><div class="hero-bottom"><a class="scroll-cue" href="#film" aria-label="Scroll to the film">↓</a></div></section>
<div class="experience-bar">${watch()}<a href="#sound" class="text-link">Explore the sound <span>↗</span></a><span>05.03.2027</span></div>
<section id="film" class="film-about pad flow-section"><span class="kicker reveal">THE FILM</span><div class="reveal"><h2>AN UNCOMPROMISING COP.<br><em>A WORLD YET TO UNFOLD.</em></h2><p>Prabhas leads Spirit, written and directed by Sandeep Reddy Vanga. T-Series describes an action drama centered on a fierce, uncompromising police officer.</p><p>The Sound Story opens a door into that world. The rest of his story is still to come.</p><a class="text-link" href="#cast">Meet the cast <span>↓</span></a></div></section>
<section id="cast" class="cast-section flow-section"><div class="section-top pad cast-intro"><span class="kicker">THE PEOPLE OF SPIRIT</span><h2>THE CAST.</h2></div><div class="cast-hero flow-scene"><div class="cast-photo" id="cast-photo"></div><div class="cast-wash"></div><div class="cast-info" id="cast-info"><h2>PRABHAS</h2></div></div><div class="cast-tabs" role="group" aria-label="Select cast member">${cast.map((p,i)=>`<button data-person="${i}" aria-pressed="${i===0}"><small>0${i+1}</small>${p.name}</button>`).join('')}</div></section>
<section class="title-interlude flow-section" aria-label="Spirit animated title"><div class="red-haze"></div>${title()}<a href="#theatre" class="interlude-arrow" aria-label="Continue to the theatre">↓</a></section>
<section id="theatre" class="theatre-page pad flow-section"><div class="theatre-heading reveal"><span class="kicker">THE SCREENING ROOM</span><h2>SPIRIT. <em>IN MOTION.</em></h2></div><div class="screen reveal"><video id="theatre-player" src="assets/title-motion.mp4" poster="assets/title-master.jpg" controls playsinline preload="none" aria-label="Spirit Telugu Sound Story"></video><div class="screen-meta"><span>#ONEBADHABIT</span><span>TELUGU · 01:31</span></div></div><div class="screen-list"><h2>WATCH FROM T-SERIES</h2>${['telugu','hindi'].map((x,i)=>`<button data-watch="${x}"><span>0${i+1}</span><strong>${x==='telugu'?'Telugu':'Hindi'}</strong><small>Original Sound Story</small><b>▶</b></button>`).join('')}</div></section>
<section id="gallery" class="pad flow-section"><div class="page-heading reveal"><div><span class="kicker">THE GALLERY</span><h2>THE WORLD,<br><em>FRAME BY FRAME.</em></h2></div><p>Explore the images in full screen.</p></div><div class="poster-grid">${arts.map((a,i)=>`<button class="poster-card reveal" data-art="${i}"><img src="${a.src}" alt="${a.alt}" loading="lazy"><span><span>${a.title}</span><b>↗</b></span></button>`).join('')}</div></section>
<section id="sound" class="sound-page pad flow-section"><div class="sound-main"><span class="kicker">THE SOUND OF SPIRIT</span><h2>#ONEBADHABIT</h2><p>THE SOUND STORY · TELUGU</p><div class="wave" id="wave" aria-hidden="true">${'<i></i>'.repeat(64)}</div><div class="transport"><button id="rewind" aria-label="Rewind 10 seconds">↶<small>10</small></button><button id="play-audio" class="big-play" aria-label="Play Sound Story">▶</button><button id="forward" aria-label="Forward 10 seconds">↷<small>10</small></button></div><div class="seek-row"><span id="elapsed">0:00</span><input id="seek" type="range" min="0" max="100" step="0.1" value="0" aria-label="Audio playback position"><span id="duration">1:31</span></div><div class="volume-row"><label>Volume <input id="volume" type="range" min="0" max="100" value="45"><output id="volume-value">45%</output></label><button id="restart-audio" class="text-link">Restart ↺</button></div><p class="track-info" id="track-info">Supplied Telugu Sound Story · best with headphones</p><div class="audio-file-row"><label class="file-label">Choose your own audio<input id="file-audio" type="file" accept="audio/*"></label><button id="restore-audio">Restore Spirit soundtrack</button></div><div class="preferences"><label><input id="reduce" type="checkbox"> Reduced motion</label><button id="fullscreen">Fullscreen ↗</button></div></div></section>
<section id="release" class="release pad flow-section"><span class="kicker reveal">WORLD RELEASE</span><h2 class="reveal">5 MARCH <em>2027.</em></h2><div class="countdown">${['days','hours','minutes','seconds'].map(n=>`<span><b data-time="${n}">—</b>${n.toUpperCase()}</span>`).join('')}</div><p>Telugu · Hindi · Tamil · Malayalam · Kannada<br>Mandarin · Japanese · Korean</p><small>Announced theatrical release. Plans may change.</small></section>
<section id="credits" class="credits-section pad"><details><summary>Credits & sources <span>+</span></summary><div class="credits-inner"><p>An independent website concept, not affiliated with the filmmakers. Campaign photographs have been edited to remove lettering at your request. The title animation is a custom website treatment of the original Spirit artwork.</p><p>Written and directed by Sandeep Reddy Vanga. Produced by Bhushan Kumar, Pranay Reddy Vanga, Krishan Kumar and Prabhakar Reddy Vanga. Film imagery, audio and marks belong to their respective owners.</p><div class="sources">${sources.map(s=>`<a href="${s[1]}" target="_blank" rel="noopener">${s[0]} ↗</a>`).join('')}</div><p>The local campaign video is 848 × 480. Official streaming versions may offer higher quality.</p></div></details><button id="replay" class="text-link">Replay opening ↗</button></section>`;

function notify(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('show'),4000)}
function closeDialog(d){d.close();if(d.id==='menu')$('#menu-open').setAttribute('aria-expanded','false');if(d.id==='video-dialog'){$('#video-stage').replaceChildren();if(resumeAfterVideo){resumeAfterVideo=false;playAudio()}}}
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.closest('dialog'))));
$$('dialog').forEach(d=>{d.addEventListener('cancel',()=>{if(d.id==='video-dialog'){$('#video-stage').replaceChildren();if(resumeAfterVideo){resumeAfterVideo=false;playAudio()}}});d.addEventListener('close',()=>{if(d.id==='menu')$('#menu-open').setAttribute('aria-expanded','false')})});
$('#menu-open').addEventListener('click',()=>{$('#menu').showModal();$('#menu-open').setAttribute('aria-expanded','true')});
function sectionId(hash){const id=decodeURIComponent(hash.replace(/^#\/?/,''));return id==='main'||!id?'home':id}
function goToSection(hash,update=true){const id=sectionId(hash),el=document.getElementById(id);if(!el)return;if($('#menu').open)closeDialog($('#menu'));if(update)history.pushState(null,'','#'+id);el.scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});if(id==='credits')$('#credits details').open=true}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;e.preventDefault();goToSection(a.hash)});addEventListener('popstate',()=>goToSection(location.hash,false));addEventListener('hashchange',()=>goToSection(location.hash,false));
const sections=$$('#main>section[id]');const navObserver=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){$$('header nav a').forEach(a=>{const active=a.hash==='#'+e.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}},{rootMargin:'-15% 0px -60% 0px'});sections.forEach(s=>navObserver.observe(s));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>revealObserver.observe(el));
function selectScene(n){sceneIndex=n;$$('[data-scene]').forEach((el,i)=>el.classList.toggle('active',i===n));$$('[data-scene-select]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===n)));$('.star-credit span').textContent=n===0?'INDIA’S BIGGEST SUPERSTAR':'';$('.star-credit strong').textContent=n===0?'PRABHAS':'VIVEK OBEROI';window.SpiritTitle?.reveal($('.hero-title [data-spirit-title]'))}
$$('[data-scene-select]').forEach(b=>b.addEventListener('click',()=>selectScene(Number(b.dataset.sceneSelect))));
async function selectPerson(n){const v=++castVersion,p=cast[n],photo=$('#cast-photo');if(!reduced){photo.classList.add('changing');await new Promise(r=>setTimeout(r,300));if(v!==castVersion)return}photo.style.backgroundImage=`url('${arts[p.image].src}')`;photo.style.backgroundPosition=p.position;photo.style.backgroundSize=n===1?'auto 165%':'cover';photo.classList.remove('changing');$('#cast-info h2').textContent=p.name;$$('[data-person]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===n)))}
$$('[data-person]').forEach(b=>b.addEventListener('click',()=>selectPerson(Number(b.dataset.person))));selectPerson(0);
function openArt(n){activeArt=(n+arts.length)%arts.length;const a=arts[activeArt],img=new Image();img.src=a.src;img.alt=a.alt;$('#art-stage').replaceChildren(img);$('#art-caption').textContent=a.title;$('#art-count').textContent=String(activeArt+1).padStart(2,'0')+' / 02';$('#download-art').href=a.src;$('#download-art').download='spirit-'+activeArt+'.png';if(!$('#art-dialog').open)$('#art-dialog').showModal()}
$$('[data-art]').forEach(b=>b.addEventListener('click',()=>openArt(Number(b.dataset.art))));$('#art-prev').addEventListener('click',()=>openArt(activeArt-1));$('#art-next').addEventListener('click',()=>openArt(activeArt+1));$('#art-dialog').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();openArt(activeArt-1)}if(e.key==='ArrowRight'){e.preventDefault();openArt(activeArt+1)}});
function openVideo(lang){const id=lang==='hindi'?'_YhSSfXmr9c':'VCGVPiD4BP0';resumeAfterVideo=!audio.paused;audio.pause();$('#theatre-player').pause();$('#video-title').textContent='SPIRIT / SOUND STORY / '+lang.toUpperCase();$('#youtube-link').href='https://www.youtube.com/watch?v='+id;const frame=document.createElement('iframe');frame.src='https://www.youtube-nocookie.com/embed/'+id+'?autoplay=1&rel=0';frame.title='Spirit official '+lang+' Sound Story';frame.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';$('#video-stage').replaceChildren(frame);$('#video-dialog').showModal()}
$$('[data-watch]').forEach(b=>b.addEventListener('click',()=>openVideo(b.dataset.watch)));$('#theatre-player').addEventListener('play',()=>audio.pause());
window.SpiritTitle?.mountAll();window.SpiritTitle?.setReducedMotion(reduced);window.SpiritCinema?.init({canvas:$('#atmosphere'),reducedMotion:reduced,getEnergy:()=>energy});
let openingRun=0,openingActive=false,openingHideTimer;
function leaveEntry(withSound){if(!openingActive)return;openingActive=false;openingRun++;if(withSound)playAudio();$('#entry').classList.add('out');document.body.classList.remove('entering');[$('#main'),$('header'),$('footer')].forEach(el=>el.removeAttribute('inert'));$('#main').focus({preventScroll:true});window.SpiritTitle?.reveal($('.hero-title [data-spirit-title]'));openingHideTimer=setTimeout(()=>$('#entry').hidden=true,900);if(location.hash&&sectionId(location.hash)!=='home')goToSection(location.hash,false)}
function showEntry(){clearTimeout(openingHideTimer);audio.pause();$('#theatre-player').pause();openingActive=true;const run=++openingRun;$('#entry').hidden=false;$('#entry').classList.remove('out','ready');document.body.classList.add('entering');[$('#main'),$('header'),$('footer')].forEach(el=>el.setAttribute('inert',''));$('#opening-title').style.setProperty('--title-reveal','1%');$('#load-number').textContent='1%';$('#load-bar').style.width='1%';$('.loading').setAttribute('aria-valuenow','1');$('#load-label').textContent='ENTERING SPIRIT';$('#enter-sound').disabled=true;$('#enter-silent').disabled=true;$('#skip-entry').focus();window.SpiritTitle?.reveal($('#opening-title'));let assetsReady=false;
 Promise.all(['assets/title-master.jpg',...arts.map(a=>a.src)].map(src=>new Promise(resolve=>{const img=new Image();img.onload=img.onerror=resolve;img.src=src}))).then(()=>assetsReady=true);
 const start=performance.now(),duration=reduced?450:3400;function load(t){if(run!==openingRun)return;const sequence=Math.min(1,(t-start)/duration),n=Math.max(1,Math.min(assetsReady?100:94,Math.floor(sequence*100)));$('#opening-title').style.setProperty('--title-reveal',n+'%');$('#load-number').textContent=n+'%';$('#load-bar').style.width=n+'%';$('.loading').setAttribute('aria-valuenow',String(n));if(n===100){$('#load-label').textContent='SPIRIT';$('#entry').classList.add('ready');$('#enter-sound').disabled=false;$('#enter-silent').disabled=false;$('#enter-sound').focus();return}requestAnimationFrame(load)}requestAnimationFrame(load)
}
$('#enter-sound').addEventListener('click',()=>leaveEntry(true));$('#enter-silent').addEventListener('click',()=>leaveEntry(false));$('#skip-entry').addEventListener('click',()=>leaveEntry(false));$('#replay').addEventListener('click',showEntry);$('#entry').addEventListener('keydown',e=>{if(e.key==='Escape')leaveEntry(false);if(e.key==='Tab'){const buttons=$$('button:not(:disabled)',$('#entry')),i=buttons.indexOf(document.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();buttons.at(-1).focus()}else if(!e.shiftKey&&i===buttons.length-1){e.preventDefault();buttons[0].focus()}}});
bindSound();syncAudio();countdown();$('#reduce').addEventListener('change',()=>window.SpiritTitle?.setReducedMotion(reduced));showEntry();
let lastFrame=0;const waveBars=$$('#wave i');function frame(t){requestAnimationFrame(frame);if(document.hidden||t-lastFrame<33)return;lastFrame=t;if(analyser&&!audio.paused){analyser.getByteFrequencyData(bins);energy=bins.slice(0,10).reduce((a,b)=>a+b,0)/2550}else energy*=.92;const waveRect=$('#wave').getBoundingClientRect();if(waveRect.top<innerHeight&&waveRect.bottom>0)waveBars.forEach((el,i)=>el.style.height=(reduced||audio.paused?2:3+(bins?.[i]||0)*.42)+'px');const progress=scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight);$('.scroll-progress').style.transform=`scaleX(${progress})`;if(reduced||openingActive)return;const cam=window.SpiritCinema?.camera,r=$('.hero').getBoundingClientRect();if(r.bottom>0){const image=$('.scene.active');image.style.transform=`scale(1.06) translate3d(${(cam?.x||0)*9}px,${Math.min(scrollY,900)*.05}px,0)`}$$('.flow-scene').forEach(el=>{const rect=el.getBoundingClientRect();if(rect.top<innerHeight&&rect.bottom>0)el.style.setProperty('--scene-progress',Math.max(-1,Math.min(1,rect.top/innerHeight)))})}requestAnimationFrame(frame);document.addEventListener('visibilitychange',()=>{if(document.hidden){audio.pause();$('#theatre-player').pause()}});

