'use client';
import { useEffect, useId, useRef, useState, type ReactNode, type PointerEvent } from 'react';
import { AnimatePresence, motion, useMotionValue, useReducedMotion, useScroll, useSpring, useTransform } from 'framer-motion';
import Lenis from '@studio-freight/lenis';

const ASSET='/assets/';
const chapters=[['film','The film'],['cast','The presence'],['theatre','The sound'],['gallery','The archive']];
const cast=[{name:'Prabhas',role:'INDIA’S BIGGEST SUPERSTAR',src:'first-look-clean.png',position:'43% 18%'},{name:'Triptii Dimri',role:'LEADING CAST',src:'first-look-clean.png',position:'77% 13%'},{name:'Vivek Oberoi',role:'LEADING CAST',src:'vivek-clean.png',position:'46% 12%'}];
const posters=[{src:'first-look-clean.png',name:'The first look',credit:'Prabhas · Triptii Dimri'},{src:'vivek-clean.png',name:'A different shade',credit:'Vivek Oberoi'},{src:'release-hq.jpg',name:'The announcement',credit:'Spirit · World release'}];
const star='0,-44 11,-15 42,-14 18,6 26,36 0,20 -26,36 -18,6 -42,-14 -11,-15';
function Title({red=false,className=''}:{red?:boolean;className?:string}) {
 const uid=useId().replaceAll(':',''),reduce=useReducedMotion();
 return <motion.svg initial={reduce?false:{clipPath:"inset(0 100% 0 0)"}} whileInView={{clipPath:"inset(0 0% 0 0)"}} viewport={{once:false,amount:.2}} transition={{duration:reduce?0:2.2,ease:[.22,1,.36,1]}} className={`spirit-mark ${className}`} viewBox="0 0 1280 720" role="img" aria-label="Spirit"><defs><mask id={`${uid}-mask`} maskUnits="userSpaceOnUse" x="0" y="0" width="1280" height="720" style={{maskType:'luminance'}}><image href={`${ASSET}title-master.jpg`} width="1280" height="720"/><path fill="black" d="M0 0H230V95H0ZM1200 0H1280V115H1200ZM0 640H380V720H0ZM565 465H1280V720H565ZM665 145H767V243H665ZM847 145H951V243H847Z"/></mask><linearGradient id={`${uid}-metal`} x1="0" y1="0" x2="1" y2="1"><stop stopColor="#fff"/><stop offset=".3" stopColor="#9ca5af"/><stop offset=".5" stopColor="#eff2ed"/><stop offset=".6" stopColor="#42494f"/><stop offset="1" stopColor="#929da6"/></linearGradient></defs><motion.g animate={reduce?{y:0}:{y:[0,-3,0],rotate:[0,.15,0]}} transition={{duration:7,repeat:Infinity,ease:"easeInOut"}} style={{transformOrigin:"50% 50%"}}><rect width="1280" height="720" mask={`url(#${uid}-mask)`} fill={red?'#800c1d':'#eeeae1'}/></motion.g>{[717,900].map((x,i)=><g key={x} transform={`translate(${x} 198)`}><motion.g animate={reduce?{rotate:0}:{rotate:360}} transition={{duration:12+i,repeat:Infinity,ease:'linear'}}><polygon points={star} fill={`url(#${uid}-metal)`} stroke="#b8c0c7" strokeWidth=".6"/><path d="M0 0V-44L11-15ZM0 0L42-14 18 6ZM0 0L26 36 0 20ZM0 0L-26 36-18 6ZM0 0L-42-14-11-15Z" fill="#303942" opacity=".6"/></motion.g></g>)}</motion.svg>
}
function Magnetic({children,onClick,className='',label}:{children:ReactNode;onClick?:()=>void;className?:string;label?:string}) {
 const reduce=useReducedMotion(),x=useSpring(0,{stiffness:180,damping:18}),y=useSpring(0,{stiffness:180,damping:18});
 function move(e:PointerEvent<HTMLButtonElement>){if(reduce||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.hypot(dx,dy),influence=Math.max(0,1-d/Math.max(r.width,r.height));x.set(dx*.22*influence);y.set(dy*.22*influence)}
 return <motion.button className={className} aria-label={label} onClick={onClick} onPointerMove={move} onPointerLeave={()=>{x.set(0);y.set(0)}} style={{x,y}} whileTap={{scale:.97}}>{children}</motion.button>
}
function Reveal({children,className=''}:{children:ReactNode;className?:string}){const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:36}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.9,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function Modal({children,title,onClose}:{children:ReactNode;title:string;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close()},[]);return <dialog ref={ref} className="cinema-dialog" aria-label={title} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="dialog-heading"><span>{title}</span><button autoFocus onClick={onClose} aria-label="Close dialog">Close <span>×</span></button></div>{children}</dialog>}
export default function Experience(){
 const reduce=useReducedMotion(),[entered,setEntered]=useState(false),[progress,setProgress]=useState(1),[menu,setMenu]=useState(false),[person,setPerson]=useState(0),[poster,setPoster]=useState<number|null>(null),[video,setVideo]=useState(false),[playing,setPlaying]=useState(false),[elapsed,setElapsed]=useState(0),[duration,setDuration]=useState(0),[audioError,setAudioError]=useState('');
 const audio=useRef<HTMLAudioElement>(null),hero=useRef<HTMLElement>(null),lenis=useRef<Lenis|null>(null),enterButton=useRef<HTMLButtonElement>(null);
 const {scrollYProgress}=useScroll({target:hero,offset:['start start','end start']}),heroY=useTransform(scrollYProgress,[0,1],['0%','18%']),heroScale=useTransform(scrollYProgress,[0,1],[1,1.08]),heroTextY=useTransform(scrollYProgress,[0,1],['0%','28%']);
 const {scrollYProgress:total}=useScroll(),bar=useSpring(total,{stiffness:100,damping:30});
 const pointerX=useMotionValue(0),pointerY=useMotionValue(0),px=useSpring(pointerX,{stiffness:60,damping:24}),py=useSpring(pointerY,{stiffness:60,damping:24});
 useEffect(()=>{let raf=0;let loaded=false;const im=new Image();im.onload=im.onerror=()=>{loaded=true};im.src=ASSET+'first-look-clean.png';const start=performance.now();function tick(now:number){const done=Math.min(1,(now-start)/(reduce?350:2100));if(now-start>7000)loaded=true;const p=Math.max(1,Math.floor(Math.min(loaded?100:94,done*100)));setProgress(p);if(p<100)raf=requestAnimationFrame(tick)}raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[reduce]);
 useEffect(()=>{if(!entered){document.body.style.overflow='hidden';return()=>{document.body.style.overflow=''}}document.body.style.overflow='';if(reduce)return;const scroller=new Lenis({duration:1.15,smoothWheel:true});lenis.current=scroller;let raf=0;function tick(t:number){scroller.raf(t);raf=requestAnimationFrame(tick)}raf=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(raf);scroller.destroy();lenis.current=null}},[entered,reduce]);
 useEffect(()=>{if(progress===100&&!entered)enterButton.current?.focus()},[progress,entered]);
 useEffect(()=>{if(menu||poster!==null||video)lenis.current?.stop();else if(entered)lenis.current?.start()},[menu,poster,video,entered]);
 function enter(sound:boolean){setEntered(true);if(sound)void play();setTimeout(()=>document.getElementById('hero-heading')?.focus({preventScroll:true}),700)}
 async function play(){if(!audio.current)return;try{audio.current.volume=.45;await audio.current.play();setAudioError('')}catch{setAudioError('Audio could not start. Tap play to try again.')}}
 function toggle(){if(audio.current?.paused)void play();else audio.current?.pause()}
 function go(id:string){setMenu(false);const target=document.getElementById(id);if(target){lenis.current?.start();if(lenis.current)lenis.current.scrollTo(target,{offset:-80});else target.scrollIntoView({behavior:reduce?'instant':'smooth'});history.replaceState(null,'',`#${id}`)}}
 function showVideo(){audio.current?.pause();setVideo(true)}
 const time=(s:number)=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
 return <><a className="skip-link" href="#film">Skip to content</a><audio ref={audio} src={`${ASSET}one-bad-habit-telugu.mp3`} preload="metadata" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onTimeUpdate={()=>setElapsed(audio.current?.currentTime||0)} onLoadedMetadata={()=>setDuration(audio.current?.duration||0)} onError={()=>setAudioError('The soundtrack is unavailable. Please try again later.')}/>
 <AnimatePresence>{!entered&&<motion.section className="opening" role="dialog" aria-modal="true" aria-label="Enter Spirit" exit={{opacity:0,filter:reduce?'none':'blur(8px)'}} transition={{duration:.7}}><span className="opening-top">A SANDEEP REDDY VANGA FILM</span><div className="opening-art"><motion.div initial={{clipPath:'inset(0 100% 0 0)'}} animate={{clipPath:`inset(0 ${100-progress}% 0 0)`}} transition={{duration:.15}}><Title red/></motion.div><div className="opening-progress"><span style={{width:`${progress}%`}}/></div><div className="opening-meta"><span>ENTERING SPIRIT</span><span role="status" aria-live="off">{progress}%</span></div><div className="opening-actions"><button ref={enterButton} disabled={progress<100} onClick={()=>enter(true)}>Enter with sound <span>↗</span></button><button disabled={progress<100} onClick={()=>enter(false)}>Enter silently</button></div></div><span className="opening-bottom">HEADPHONES ON. WORLD OFF.</span></motion.section>}</AnimatePresence>
 <div inert={!entered}>
 <motion.div className="reading-progress" style={{scaleX:bar}}/>
 <header className="site-header"><button className="nav-mark" onClick={()=>go('home')} aria-label="Spirit home"><Title/></button><nav className="desktop-nav" aria-label="Main navigation">{chapters.map(([id,name])=><button key={id} onClick={()=>go(id)}>{name}</button>)}</nav><div className="header-tools"><button className={`sound-switch ${playing?'is-playing':''}`} onClick={toggle} aria-pressed={playing} aria-label={playing?'Pause soundtrack':'Play soundtrack'}><span className="equalizer" aria-hidden="true">{[0,1,2,3].map(i=><i key={i}/>)}</span><span>Sound {playing?'on':'off'}</span></button><button className="menu-trigger" onClick={()=>setMenu(true)} aria-expanded={menu} aria-label="Open navigation"><span/><span/></button></div></header>
 <main>
 <section ref={hero} id="home" className="hero-scene" onPointerMove={e=>{if(reduce||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();pointerX.set((e.clientX/r.width-.5)*10);pointerY.set(((e.clientY-r.top)/r.height-.5)*8)}} onPointerLeave={()=>{pointerX.set(0);pointerY.set(0)}}>
 <motion.div className="hero-camera" style={{y:reduce?0:heroY,scale:reduce?1:heroScale}}><motion.img style={{x:px,y:py}} src={`${ASSET}first-look-clean.png`} alt="Prabhas and Triptii Dimri in the Spirit first-look artwork" fetchPriority="high" className="hero-photo"/></motion.div><div className="hero-vignette"/><div className="film-grain" aria-hidden="true"/>
 <div className="hero-topline"><span>BHADRAKALI PICTURES · T-SERIES</span><span>AN INDEPENDENT FAN EXPERIENCE</span></div>
 <motion.div className="hero-copy" style={{y:reduce?0:heroTextY}}><p className="eyebrow"><i/> INDIA’S BIGGEST SUPERSTAR</p><h1 id="hero-heading" tabIndex={-1}>PRABHAS</h1><div className="hero-title"><Title/></div><p className="director-line">A FILM BY <strong>SANDEEP REDDY VANGA</strong></p><div className="hero-actions"><Magnetic className="primary-action" onClick={showVideo}><span className="play-symbol">▶</span> Watch the sound story <span>↗</span></Magnetic><button className="understated" onClick={()=>go('film')}>Explore the film <span>↓</span></button></div></motion.div>
 <div className="hero-bottom"><button onClick={()=>go('film')} className="scroll-cue"><span className="scroll-line"/>SCROLL TO ENTER THE WORLD</button><div className="release-stamp"><small>WORLDWIDE IN CINEMAS</small><strong>05 <span>/</span> 03 <span>/</span> 2027</strong></div><span className="edition">01 — THE ARRIVAL</span></div>
 </section>
 <section className="film-section section-pad" id="film"><div className="section-top"><span>01 / THE FILM</span><span>A NEW CHAPTER</span></div><div className="film-grid"><Reveal><p className="eyebrow">PRABHAS × SANDEEP REDDY VANGA</p><h2>ONE BAD<br/><em>HABIT.</em></h2><p className="film-note">A new collaboration. An unmistakable presence.<br/>Step inside the world of <i>Spirit.</i></p><button className="line-link" onClick={()=>go('cast')}>Meet the presence <span>↗</span></button></Reveal><Reveal className="film-detail"><div className="detail-window"><img src={`${ASSET}first-look-clean.png`} alt="Detail from Spirit’s first-look campaign" loading="lazy"/><span className="frame-corner tl"/><span className="frame-corner br"/></div><div className="image-caption"><span>SPIRIT — THE FIRST LOOK</span><span>01 / 03</span></div></Reveal></div><div className="film-facts"><div><small>WRITTEN & DIRECTED BY</small><p>Sandeep Reddy Vanga</p></div><div><small>PRESENTED BY</small><p>Gulshan Kumar & T-Series</p></div><div><small>PRODUCTION</small><p>T-Series · Bhadrakali Pictures</p></div></div></section>
 <section className="officer-section" aria-label="Prabhas IPS officer concept"><motion.img src={`${ASSET}prabhas-officer-concept.png`} alt="AI-generated fan concept of Prabhas in a khaki police uniform in a cinematic stone hall" loading="lazy" initial={reduce?false:{scale:1.07}} whileInView={{scale:1}} viewport={{once:false,amount:.15}} transition={{duration:3,ease:[.22,1,.36,1]}}/><div className="officer-shade"/><div className="officer-copy"><Reveal><p className="eyebrow">PRABHAS / THE OFFICER</p><Title/><h2>COMMANDING<br/><em>PRESENCE.</em></h2></Reveal></div><div className="officer-caption"><span>IPS OFFICER LOOK</span><span>AI-GENERATED FAN CONCEPT</span></div></section>
 <section id="cast" className="cast-section"><div className="cast-heading section-pad"><span>02 / THE PRESENCE</span><Reveal><h2>THE PEOPLE.<br/><em>THE POWER.</em></h2></Reveal><p>Three names.<br/>One world.</p></div><div className="cast-stage" role="tabpanel" id="cast-panel" aria-label={cast[person].name}><AnimatePresence mode="wait"><motion.img key={person} src={`${ASSET}${cast[person].src}`} alt={cast[person].name} style={{objectPosition:cast[person].position}} initial={{opacity:0,scale:reduce?1:1.06}} animate={{opacity:1,scale:1}} exit={{opacity:0}} transition={{duration:.65}}/></AnimatePresence><div className="cast-shade"/><div className="cast-caption"><AnimatePresence mode="wait"><motion.div key={person} initial={{opacity:0,y:reduce?0:18}} animate={{opacity:1,y:0}} exit={{opacity:0}}><span>{cast[person].role}</span><h3>{cast[person].name}</h3></motion.div></AnimatePresence><span className="cast-counter">0{person+1}<small>/ 03</small></span></div></div><div className="cast-tabs" role="tablist" aria-label="Featured cast">{cast.map((p,i)=><button role="tab" aria-controls="cast-panel" tabIndex={person===i?0:-1} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(person+(e.key==='ArrowRight'?1:2))%3;setPerson(next);const tabs=e.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('[role=tab]');tabs?.[next]?.focus()}}} aria-selected={person===i} key={p.name} onClick={()=>setPerson(i)}><small>0{i+1}</small>{p.name}<span>↗</span>{person===i&&<motion.i layoutId="cast-active" transition={{type:'spring',stiffness:200,damping:27}}/>}</button>)}</div></section>
 <section className="sound-section section-pad" id="theatre"><div className="section-top"><span>03 / THE SOUND</span><span>FEEL IT BEFORE YOU SEE IT</span></div><Reveal><p className="eyebrow">THE TELUGU SOUND STORY</p><h2>EVERY STORY<br/>HAS A <em>SOUND.</em></h2></Reveal><div className={`sound-wave ${playing?'active':''}`} aria-hidden="true">{Array.from({length:72},(_,i)=><i key={i} style={{height:`${Math.round(12+Math.abs(Math.sin(i*.48)*Math.cos(i*.17))*88)}%`,animationDelay:`${(i*.029).toFixed(3)}s`}}/>)}</div><div className="sound-console"><Magnetic className="round-play" onClick={toggle} label={playing?'Pause sound story':'Play sound story'}>{playing?'Ⅱ':'▶'}</Magnetic><div className="track-info"><span>SPIRIT — #ONEBADHABIT</span><small>TELUGU · SOUND STORY</small></div><span className="track-time">{time(elapsed)} <i>/ {time(duration)}</i></span></div><input className="audio-seek" aria-label="Sound story playback position" type="range" min={0} max={duration||1} step="0.1" value={elapsed} onChange={e=>{if(audio.current)audio.current.currentTime=Number(e.target.value)}}/><div className="sound-footer"><span>HEADPHONES RECOMMENDED</span><button onClick={showVideo}>Watch the official sound story ↗</button></div>{audioError&&<p role="alert">{audioError}</p>}</section>
 <section id="gallery" className="gallery-section section-pad"><div className="section-top"><span>04 / THE ARCHIVE</span><span>EVERY FRAME, A STATEMENT</span></div><div className="gallery-heading"><Reveal><h2>HOLD THE<br/><em>FRAME.</em></h2></Reveal><p>A closer look at the world<br/>of Spirit. Select to explore.</p></div><div className="poster-grid">{posters.map((p,i)=><Reveal key={p.src}><motion.button className="poster-button" onClick={()=>setPoster(i)} whileHover={reduce?{}:{y:-8}} transition={{type:'spring',stiffness:160,damping:22}}><div className="poster-image"><img src={`${ASSET}${p.src}`} alt={p.credit} loading="lazy"/><span className="poster-open">↗</span></div><div className="poster-caption"><span><small>0{i+1}</small>{p.name}</span><span>↗</span></div></motion.button></Reveal>)}</div></section>
 <section className="release-section section-pad"><Reveal><span className="eyebrow">THE WAIT HAS A DATE</span><h2>05.03.<em>2027</em></h2><p>WORLDWIDE. ONLY IN CINEMAS.</p></Reveal><div className="release-languages">TELUGU · HINDI · TAMIL · MALAYALAM · KANNADA<br/>MANDARIN · JAPANESE · KOREAN</div><small>Announced release date. Subject to change.</small></section>
 </main><footer className="site-footer section-pad"><div className="footer-main"><Title/><div><span>A FILM BY</span><p>SANDEEP REDDY VANGA</p></div><button className="back-top" onClick={()=>go('home')} aria-label="Back to top">↑</button></div><div className="footer-bottom"><p>Independent fan concept. Not affiliated with the filmmakers.<br/>Film imagery, audio and marks belong to their respective owners.</p><a href="https://www.instagram.com/inspiritmode/" target="_blank" rel="noreferrer">Follow Spirit ↗</a><button onClick={()=>{setProgress(100);setEntered(false);audio.current?.pause();window.scrollTo(0,0)}}>Replay opening ↗</button></div></footer></div>
 {menu&&<Modal title="CHOOSE YOUR CHAPTER" onClose={()=>setMenu(false)}><nav className="chapter-menu">{chapters.map(([id,name],i)=><button key={id} onClick={()=>go(id)}><small>0{i+1}</small>{name}<span>↗</span></button>)}</nav></Modal>}
 {video&&<Modal title="SPIRIT / THE OFFICIAL SOUND STORY" onClose={()=>setVideo(false)}><div className="video-frame"><iframe src="https://www.youtube-nocookie.com/embed/VCGVPiD4BP0?autoplay=1&rel=0" title="Spirit Telugu Sound Story — T-Series" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/></div><a className="video-fallback" href="https://www.youtube.com/watch?v=VCGVPiD4BP0" target="_blank" rel="noreferrer">Open on YouTube ↗</a></Modal>}
 {poster!==null&&<Modal title={posters[poster].name.toUpperCase()} onClose={()=>setPoster(null)}><img className="lightbox-image" src={`${ASSET}${posters[poster].src}`} alt={posters[poster].credit}/><div className="lightbox-controls"><button onClick={()=>setPoster((poster+posters.length-1)%posters.length)}>← Previous</button><span>{poster+1} / {posters.length}</span><button onClick={()=>setPoster((poster+1)%posters.length)}>Next →</button><a download href={`${ASSET}${posters[poster].src}`}>Download ↓</a></div></Modal>}
 </>
}
